class VearchException(Exception):
    def __init__(self):
        pass
